### ISSUE TITLE
pretrained_path

### ISSUE THREAD

**Issue by Liu-arch** [mrluin/TextualDegRemoval#11]
Can you share the pretrained_stable_diffusion_path and pretrained_clip_model_path file?

**Comment by mrluin** [comment]
Hello, you can download pre-trained models from these:
pretrained_stable_diffusion_path: https://huggingface.co/stabilityai/stable-diffusion-2-1-base
pretrained_clip_model_path: https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K

**Comment by Liu-arch** [comment]
Thank you very much！
