### ISSUE TITLE
--opt path_to_options

### ISSUE THREAD

**Issue by Liu-arch** [mrluin/TextualDegRemoval#14]
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port=1234 scripts/train/main_train_restoration_with_ref_input.py --opt path_to_options --dist True
    Can you make the file --opt path_to_options public?

**Comment by mrluin** [comment]
Hello, thanks for your attention. opt files are provided in options directory, you can use corresponding options to train your mapper or ref-based restoration network.
