### ISSUE TITLE
Can you provide Data and Pretrained models？

### ISSUE THREAD

**Issue by GuochaoCS** [mrluin/TextualDegRemoval#4]
Thank you for your interest in my method and its performance. To reproduce the results, I recommend using the pretrained model and dataset provided in the GitHub repository. You can find the necessary resources there for replicating the method. Let me know if you need any further assistance.

**Comment by mrluin** [comment]
Thanks for your attention. I will update related instructions in the next few weeks.

**Comment by XDUcy** [comment]
Any progress so far?
