### ISSUE TITLE
请问什么时候能够公开预训练模型？

### ISSUE THREAD

**Issue by tonia86** [mrluin/TextualDegRemoval#9]
您的工作非常有意思，感谢您能够上传所提方法的论文。同时，想问一下您，什么时候能够公开预训练模型？

**Comment by mrluin** [comment]
您好，感谢关注！这个项目是我在华为实习期间做的，由于当时代码和模型都在公司那边的server上无法开源，最近比较忙，如果有时间的话，我会重新训练一下并上传预训练模型。同时，关于第一阶段的Mapper训练速度其实还算是比较快，感兴趣的话可以根据代码进行复现，如果有问题欢迎随时提出！
